name: Deploy to Server

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch yang akan di-deploy'
        required: true
        default: 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script_stop: true
          script: |
            cd /var/www/html/rental_dgreen

            npm run build
            php artisan optimize:clear
            php artisan optimize
            php artisan filament:optimize
